## This chart relies on the common library chart from bjw-s
## You can find it and the values you can provide and modify, at https://github.com/bjw-s/helm-charts/blob/common-3.1.0/charts/library/common/values.yaml
## Refer there for more detail about the supported values.
## Any values that you find in the above `values.yaml` can be provided to this chart and are then rendered.

controllers:
  trilium:
    containers:
      trilium:
        image:
          repository: zadam/trilium
          tag: 0.63.5
          pullPolicy: IfNotPresent
        env:
          key: "value"

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim:
#ingress:
#  main:
#    enabled: true
#    annotations:
#      # proxy-body-size is set to 0 to remove the body limit on file uploads
#      nginx.ingress.kubernetes.io/proxy-body-size: "0"
#    hosts:
#      - host: trilium.local
#        paths:
#          - path: "/api/v1"
#    tls: []

