apiVersion: v2
type: application
name: trilium
home: https://github.com/TriliumNext/helm-chart
icon: https://github.com/TriliumNext/helm-chart/commit/icon.png
deprecated: false
description: |-
  Build your personal knowledge base with Trilium Notes. A hierarchical note taking application with focus on building large personal knowledge bases.
annotations:
  category: Notes
version: 0.0.2
appVersion: 0.63.6
kubeVersion: ">= 1.19"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.2.1
keywords:
  - electron
  - wiki
  - notebook
  - notes
  - self-hosted
  - knowledge-graph
  - electron-app
  - note-taking
  - self-hosting
  - knowledge-base
  - personal-knowledge-base
  - knowledge-management
  - personal-wiki
  - notes-app
  - scriptable
  - knowledge-management-graph
  - note-managment
  - note-taker
  - local-first
maintainers:
  - name: trilium
    url: https://github.com/zadam/trilium
  - name: perfectra1n
    email: jon@jonfuller.io
    url: https://perf3ct.tech
sources:
  - https://github.com/TriliumNext/helm-chart
  - https://github.com/zadam/trilium
